services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./php
    user: "www-data"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: elasticsearch:7.17.22
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  rag-backend:
    build: ./rag
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - MAGENTO_DB_HOST=mysql
      - MAGENTO_DB_NAME=magento
      - MAGENTO_DB_USER=magento
      - MAGENTO_DB_PASS=magento
      - OLLAMA_MODEL=qwen2.5:0.5b
    depends_on:
      - qdrant
      - ollama
      - mysql
    volumes:
      - ./rag/pdfs:/app/pdfs  # thư mục chứa PDF

volumes:
  mysql_data:
  qdrant_data:
  ollama_data:
