upstream fastcgi_backend {
    server php:9000;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/html/src/pub;

    index index.php;

    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /static/ {
        expires max;

        location ~ ^/static/version\d*/ {
            rewrite ^/static/version\d*/(.*)$ /static/$1 last;
        }

        location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|woff|woff2|eot|ttf|otf)$ {
            add_header Cache-Control "public";
            add_header X-Frame-Options "SAMEORIGIN";
            try_files $uri $uri/ /static.php?resource=$uri;
        }

        if (!-f $request_filename) {
            rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
        }
    }

    location /media/ {
        try_files $uri $uri/ /get.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass fastcgi_backend;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        include fastcgi_params;
    }
}
